In [1]:
import torch
import torch.nn as nn

In [2]:
conv = nn.Conv2d(1,1,3)
conv.bias.data[0]=0

In [3]:
for i in range(3):
    for j in range(3):
        conv.weight.data[0][0][i][j] = i+j

In [4]:
conv.weight

Parameter containing:
tensor([[[[0., 1., 2.],
          [1., 2., 3.],
          [2., 3., 4.]]]], requires_grad=True)

In [6]:
in_data=torch.Tensor(1,1,32,32)

In [7]:
for i in range(32):
    for j in range(32):
        in_data[0][0][i][j] = i+j

In [8]:
in_data

tensor([[[[ 0.,  1.,  2.,  ..., 29., 30., 31.],
          [ 1.,  2.,  3.,  ..., 30., 31., 32.],
          [ 2.,  3.,  4.,  ..., 31., 32., 33.],
          ...,
          [29., 30., 31.,  ..., 58., 59., 60.],
          [30., 31., 32.,  ..., 59., 60., 61.],
          [31., 32., 33.,  ..., 60., 61., 62.]]]])

In [9]:
out = conv(in_data)

In [18]:
out[0][0]

tensor([[  48.,   66.,   84.,  102.,  120.,  138.,  156.,  174.,  192.,  210.,
          228.,  246.,  264.,  282.,  300.,  318.,  336.,  354.,  372.,  390.,
          408.,  426.,  444.,  462.,  480.,  498.,  516.,  534.,  552.,  570.],
        [  66.,   84.,  102.,  120.,  138.,  156.,  174.,  192.,  210.,  228.,
          246.,  264.,  282.,  300.,  318.,  336.,  354.,  372.,  390.,  408.,
          426.,  444.,  462.,  480.,  498.,  516.,  534.,  552.,  570.,  588.],
        [  84.,  102.,  120.,  138.,  156.,  174.,  192.,  210.,  228.,  246.,
          264.,  282.,  300.,  318.,  336.,  354.,  372.,  390.,  408.,  426.,
          444.,  462.,  480.,  498.,  516.,  534.,  552.,  570.,  588.,  606.],
        [ 102.,  120.,  138.,  156.,  174.,  192.,  210.,  228.,  246.,  264.,
          282.,  300.,  318.,  336.,  354.,  372.,  390.,  408.,  426.,  444.,
          462.,  480.,  498.,  516.,  534.,  552.,  570.,  588.,  606.,  624.],
        [ 120.,  138.,  156.,  174.,  192.,  210

48